### ISSUE TITLE
Select two storm tracking algorithms

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/roadmap#20]
Identify two extratropical cyclone tracking algorithms (one simple, one complex) that would be relevant to deploy in DACCS. 

Expected deliverables:
- [ ] List of algorithms considered (brief lit. review and software review)
- [ ] Rationale for selection 
- [ ] Brief explanation for each algorithm and relevant references

Estimated effort: 2 days

**Comment by huard** [comment]
Document (in french) by Hélène Côté (Ouranos) suggests 
-  Wang et al. 2013 (based on Serreze)
- TRACK, from Hodges
